In [1]:
import torch

In [2]:
# 张量表示一个由数值组成的数组，这个数组可能有很多维度
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
# 我们可以通过张量的shape属性来访问张量的形状和张量中元素的总数(num of elements)
print(x.shape)
print(x.numel())

torch.Size([12])
12


In [6]:
# 要改变一个张量的形状而不改变元素的数量和元素值，我们可以调用reshape函数
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
# 使用全0、全1、其他常量或者从特定分布中随机采样数字
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.tensor([[1, 2, 3, 4], [2, 3, 5, 6],[1, 2, 6, 1]])

tensor([[1, 2, 3, 4],
        [2, 3, 5, 6],
        [1, 2, 6, 1]])

In [10]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [11]:
# 进行指数运算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [12]:
# 我们也可以把多个张量连结在一起
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [13]:
# 通过逻辑运算符构建一个二维张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [14]:
# 对张量当中所有元素求和可以得到一个只有一个元素的张量
X.sum()

tensor(66.)

In [22]:
# 即使形状不同，我们仍然可以通过调用广播机制来执行按元素操作
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [7]:
# 可以用[-1]选择最后一行元素，可以用[1:3]选择第二行和第三行元素
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
X, X[-1], X[1:3], X[:, 1]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([1., 5., 9.]))

In [2]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [4]:
# 除读取外，我们还可以通过指定索引(位于1行2列的那个元素），来将元素写入矩阵
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [5]:
# 为多个元素赋值相同的值，我们只需要索引所有元素，然后为他们赋值
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [9]:
# 转换为NumPy张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [10]:
# 将大小为1的张量转换为Python张量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [20]:
# 数据预处理
# 创建一个人工数据集，并存储在csv（逗号分隔值）文件
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [22]:
# 从创建的csv文件当中加载原始数据集
import pandas as pd
data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [23]:
# 为了处理缺失的数据，典型的方法包括插值和处理，这里，我们将考虑插值
# iloc的意思是index of location
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [24]:
# 对于inputs当中的类别值或离散值，我们将“NaN"视作一个类别
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)
# 生成的结果类似于独热编码，Alley_Pave代表Alley值为Pave的行值为1，Alley_nan代表Alley值为nan的行值为1

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [27]:
# 现在inputs和outputs当中的所有条目都是数值类型，它们可以转换成张量格式
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [2]:
# 补充一个比较奇怪的点
# 下面这种情况，当改变a的时候b也会跟着改变
a = torch.arange(12)
b = a.reshape((3, 4))
b[:] = 2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
# 自学心得，关于pytorch数组维度的问题
a = torch.arange(12).reshape(3, 4)
print(a)
print(a.shape)
# 输出第2行及其维度
b = a[1, :]
print(b)
print(b.shape)
# 输出第二列及其维度
c = a[:, 1]
print(c)
print(c.shape)
# 如果是这样：输出才是1X3
d = torch.tensor([[1, 5, 9]])
print(d)
print(d.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
tensor([4, 5, 6, 7])
torch.Size([4])
tensor([1, 5, 9])
torch.Size([3])
tensor([[1, 5, 9]])
torch.Size([1, 3])
